#!/bin/bash

. scripts/default

if [ ! -e $DL_DIR/$KRNTAR ]; then
	PushD $DL_DIR
	wget $KRNURL
	PopD
fi

if [ -e $WORK_DIR/$KRN/vmlinux ]; then
	echo "Already exist"
	exit 0
fi

PushD $WORK_DIR

tar Jxf $DL_DIR/$KRNTAR
cd $KRN

make defconfig
sed \
	-e 's/.*CONFIG_VIRTIO_PCI.*/CONFIG_VIRTIO_PCI=y/' \
	-e 's/.*CONFIG_VERTIO_NET.*/CONFIG_VIRTIO_NET=y/' \
	-e 's/.*CONFIG_PARAVIRT_GUEST.*/CONFIG_PARAVIRT_GUEST=y/' \
	-e 's/.*CONFIG_PREEMPT_NONE.*/CONFIG_PREEMPT_NONE=y/' \
	-e 's/.*CONFIG_PREEMPT_VOLUNTARY.*/CONFIG_PREEMPT_VOLUNTARY=n/' \
	-e 's/.*CONFIG_SECURITY.*/CONFIG_SECURITY=n/' \
	-e 's/.*CONFIG_EXT3_FS.*/CONFIG_EXT3_FS=n/' \
	-e 's/.*CONFIG_EXT4_FS.*/CONFIG_EXT4_FS=y/' \
	-e 's/.*CONFIG_STACKTRACE.*/CONFIG_STACKTRACE=n/' \
	-e 's/.*CONFIG_SOUND.*/CONFIG_SOUND=n/' \
	-e 's/.*CONFIG_YENTA.*/CONFIG_YENTA=n/' \
	-e 's/.*CONFIG_WIRELESS.*/CONFIG_WIRELESS=n/' \
	-e 's/.*CONFIG_MAC80211.*/CONFIG_MAC80211=n/' \
	-e 's/.*CONFIG_RFKILL.*/CONFIG_RFKILL=n/' \
	-e 's/.*CONFIG_WLAN.*/CONFIG_WLAN=n/' \
	-e 's/.*CONFIG_IPV6.*/CONFIG_IPV6=n/' \
	-e 's/.*CONFIG_NET_VENDOR_3COM.*/CONFIG_NET_VENDOR_3COM=n/' \
	-e 's/.*CONFIG_NET_VENDOR_ADAPTEC.*/CONFIG_NET_VENDOR_ADAPTEC=n/' \
	-e 's/.*CONFIG_NET_VENDOR_ALTEON.*/CONFIG_NET_VENDOR_ALTEON=n/' \
	-e 's/.*CONFIG_NET_VENDOR_AMD.*/CONFIG_NET_VENDOR_AMD=n/' \
	-e 's/.*CONFIG_NET_VENDOR_ATHEROS.*/CONFIG_NET_VENDOR_ATHEROS=n/' \
	-e 's/.*CONFIG_NET_VENDOR_BROADCOM.*/CONFIG_NET_VENDOR_BROADCOM=n/' \
	-e 's/.*CONFIG_NET_VENDOR_BROCADE.*/CONFIG_NET_VENDOR_BROCADE=n/' \
	-e 's/.*CONFIG_NET_VENDOR_CHELSIO.*/CONFIG_NET_VENDOR_CHELSIO=n/' \
	-e 's/.*CONFIG_NET_VENDOR_DLINK.*/CONFIG_NET_VENDOR_DLINK=n/' \
	-e 's/.*CONFIG_NET_VENDOR_EMULEX.*/CONFIG_NET_VENDOR_EMULEX=n/' \
	-e 's/.*CONFIG_NET_VENDOR_EXAR.*/CONFIG_NET_VENDOR_EXAR=n/' \
	-e 's/.*CONFIG_NET_VENDOR_FUJITSU.*/CONFIG_NET_VENDOR_FUJITSU=n/' \
	-e 's/.*CONFIG_NET_VENDOR_HP.*/CONFIG_NET_VENDOR_HP=n/' \
	-e 's/.*CONFIG_NET_VENDOR_MARVELL.*/CONFIG_NET_VENDOR_MARVELL=n/' \
	-e 's/.*CONFIG_NET_VENDOR_NVIDIA.*/CONFIG_NET_VENDOR_NVIDIA=n/' \
	-e 's/.*CONFIG_FDDI.*/CONFIG_FDDI=n/' \
	-e 's/.*CONFIG_EDAC.*/CONFIG_EDAC=n/' \
	-e 's/.*CONFIG_QUOTA.*/CONFIG_QUOTA=n/' \
	-e 's/.*CONFIG_DEBUG_KERNEL.*/CONFIG_DEBUG_KERNEL=n/' \
	-e 's/.*CONFIG_PERF_EVENTS.*/CONFIG_PERF_EVENTS=n/' \
	-e 's/.*CONFIG_PROFILING.*/CONFIG_PROFILING=n/' \
	-e 's/.*CONFIG_TRACEPOINTS.*/CONFIG_TRACEPOINTS=n/' \
	-e 's/.*CONFIG_USB.*/CONFIG_USB=n/' \
	.config > mini.config
echo "CONFIG_VIRTIO_NET=y" >> mini.config
echo "CONFIG_KVM_CLOCK=y" >> mini.config
echo "CONFIG_KVM_GUEST=y" >> mini.config
make KCONFIG_ALLCONFIG=mini.config allnoconfig

Make bzImage

PopD
